### ISSUE TITLE
Support needed for variable-COLRv1

### ISSUE THREAD

**Issue by vv-monsalve** [SophiaDesign/Foldit#2]
@SophiaDesign reported

> I am still puzzled with the same problem. Report (in github actions) says there should be exported font files, but there is nothing there still. Instead of a build script I have the makefile from the Google Fonts template.

Could you please point out (provide a link as a comment here) the Report where this has been said?. When inspecting the [Actions](https://github.com/SophiaDesign/GF-Foldit/actions) tab, everything looks like they are working.

On the other hand, it is always helpful to run the exporting process directly from the Glyphs app to validate it is working from there. After trying to do so as a VF, Glyphs reports an issue regarding active instances.

<img width="425" alt="Screen Shot 2022-04-07 at 8 32 42" src="https://user-images.githubusercontent.com/48698976/162215752-e2639ba1-b17a-4f2c-b38a-accb69cb01d7.png">

And when trying to export static TTF there are other issues reported.

<img width="840" alt="Screen Shot 2022-04-07 at 8 39 17" src="https://user-images.githubusercontent.com/48698976/162215971-b9c71994-8da9-48ea-9e11-8d4a2c9f2c5b.png">
<img width="831" alt="Screen Shot 2022-04-07 at 8 44 24" src="https://user-images.githubusercontent.com/48698976/162215980-3d534931-be9d-49c8-b58f-38848c7ee2a3.png">

You would like to fix all the above to have exported fonts from the app and then try to run the `make build` again from the repo.

**Comment by Lorp** [comment]
@SophiaDesign just added me. Nice project.

> When testing it on [Samsa](https://www.axis-praxis.org/samsa/) the colr axis seems to not be working yet

Indeed Samsa does not currently support any flavour of COLR. Funds permitting, I am keen to add COLRv0 and COLRv1 including the new variation features such as “component” rotation and variable start/end points for gradients, etc.

**Comment by SophiaDesign** [comment]
> Yes, I know, I meant support for _variable_ COLRv1, not simply COLRv1. The former is not supported anywhere that I know of right now

Could [Plakato Color](https://underware.nl/fonts/plakato/features/color/#feature_info) be an example for this? 

If this is a COLRv1 gradient variable feature that works on Chrome, then can we assume the problem is either with the Glyphs file or exporting process? Are there any restrictions on gradient interpolations like number of gradient points or point-placement that I should be aware of? @anthrotype 

Unless there are any other reasons that it would still not render accurately on FontGoggles or Axis-Praxis, even if the example above works in Chrome? @Lorp @justvanrossum

**Comment by justvanrossum** [comment]
Plakato is non-variable COLRv1, and anything you see that makes it looks otherwise has been cleverly emulated.

I'm missing some context in this discussion, but there is an open blackrenderer (and therefore FontGoggles) issue regarding sweep gradients, and an open issue about padding behavior for gradients in general. So if you're using those, I'd not be surprised if you get unexpected results. (Btw. Chrome _also_ has an issue with sweep gradients.)

If you see other unexpected things in FontGoggles, I'd love to hear about it.

**Comment by SophiaDesign** [comment]
> Plakato is non-variable COLRv1, and anything you see that makes it looks otherwise has been cleverly emulated.

Thanks for clearing this, I was deceived by those social media hashtags indeed!

> I'm missing some context in this discussion, but there is an open blackrenderer (and therefore FontGoggles) issue regarding sweep gradients, and an open issue about padding behavior for gradients in general. So if you're using those, I'd not be surprised if you get unexpected results. (Btw. Chrome _also_ has an issue with sweep gradients.)

I did not know that Blackrenderer and FontGoggles were related, thanks for this. I tried a few outputs with blackrenderer yesterday and got the same results [as what is shown in FontGoggles](https://github.com/SophiaDesign/GF-Foldit/issues/2#issuecomment-1095408509)


**Any suggestions on what I could use to test if the font is working?** Who would be good people to poke at regarding Chrome and Blackrenderer support for sweep gradient?

**Comment by justvanrossum** [comment]
The effect you desire (if I look at the two static fonts) is not possible without variable-COLRv1. 

What you're seeing is the gradients for the ThinCondensed font being applied to the whole range on the Weight axis.

To build a variable COLRv1 font (*), we'll need:
- https://github.com/fonttools/fonttools/issues/2328

For such a font to preview in FontGoggles/blackrenderer, we'll need:
- https://github.com/BlackFoundryCom/black-renderer/issues/53

For such a font to work in Chrome we'll need:
- https://bugs.chromium.org/p/chromium/issues/detail?id=1311241

So it appears we are quite far removed from realizing your design in true variable form.

*) While it is possible to build variable COLRv1 with code, it is currently quite a hassle.

(FontGoggles is related to blackrenderer in that it uses blackrenderer for its COLRv1 support.)

So, @davelab6: this design is an excellent use case for variable COLRv1, and can be used to try to convince the Higher Powers to put more priority on support for it in Chrome.

**Comment by justvanrossum** [comment]
To clarify further: your outlines _are_ variable, and that works perfectly, but all COLRv1 Paint parameters aren't, and that is the problem.

**Comment by justvanrossum** [comment]
People to poke for fontmake/fonttools variable-COLRv1 build support: @anthrotype
People to poke for blackrenderer/FontGoggles support: me
People to poke for Chrome support: @drott

(It appears that your font is only using linear gradients, so the sweep gradient issues I alluded to earlier are not relevant here.)

**Comment by justvanrossum** [comment]
Cc @rsheeter

**Comment by SophiaDesign** [comment]
To build on [this case](https://github.com/SophiaDesign/Foldit/issues/2#issuecomment-1095408509) in the thread above (it was likely exports using `fontmake 2.4.1`)

Changed to using `gftools builder 0.9.11` and `fontmake 3.3.0`
The current result is that even the static export gradients for the **Foldit-Extrabold.ttf** export file now renders the gradient/color that was originally set for **Thin weight instance**. The static export gradients now have the same issue as the variable gradients had so far.

The test experiments with what would happen if the variable axis was to change between 2 solid colors.
So it seems the default is rendering the color settings for Thin master/instance?
Files attached: [colrv1-test-31May2022.zip](https://github.com/SophiaDesign/Foldit/files/8808171/colrv1-test-31May2022.zip)

**Expectation:**
- **Glyphs App exports (OTF):**
<img width="299" alt="Screenshot 2022-05-31 at 19 10 26" src="https://user-images.githubusercontent.com/84964395/171259845-d34afa05-e8ec-4cbc-991e-6c00b8fd6e08.png">
<img width="222" alt="Screenshot 2022-05-31 at 19 10 34" src="https://user-images.githubusercontent.com/84964395/171259849-4f35de0e-0f75-4019-afa1-00c9131a4ea3.png">


**Result:**
- **`gftools builder` exports (Variable, TTF Thin, TTF Etrabold):**
<img width="953" alt="Screenshot 2022-05-31 at 19 27 57" src="https://user-images.githubusercontent.com/84964395/171259853-7b759a5b-c71d-4627-84b4-91249610d1b7.png">
<img width="950" alt="Screenshot 2022-05-31 at 19 34 49" src="https://user-images.githubusercontent.com/84964395/171260334-8ed0c1a2-e00a-4dff-9641-235b1a570946.png">

<img width="959" alt="Screenshot 2022-05-31 at 19 34 58" src="https://user-images.githubusercontent.com/84964395/171260283-9715c586-267d-477c-945e-b14113ea9394.png">

**Comment by anthrotype** [comment]
BTW, there's a way to live preview COLRv1 VF instances inside FontGoggles by building the latter with the `blackrenderer` library from this PR branch: https://github.com/BlackFoundryCom/black-renderer/pull/88

Basically, in a fresh venv, install the above fonttools and black-renderer branches inside fontgoggles' virtual environment. To build the app as an "alias" (similar to pip install -e . but for GUI apps), I did  `python App/setup.py py2app -A`, this created an alias wrapper bundle in App/dist/FontGoggles.app that can be double clicked and run as usual.

These are the command to build FontGoggles with experimental variable COLRv1 support:

```sh
git clone https://github.com/justvanrossum/fontgoggles
cd fontgoggles
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt -r requirements-dev.txt
pip install -e git+https://github.com/anthrotype/black-renderer.git@variable-colr#egg=blackrenderer
pip install -e git+https://github.com/fonttools/fonttools.git@wip-variable-colr#egg=FontTools
pip install -e .
./Turbo/build_lib.sh
python App/setup.py py2app -A
open App/dist/FontGoggles.app
```

**Comment by SophiaDesign** [comment]
@anthrotype Thanks for explaining the steps for setting up the new blackrenderer version. Had to update my OS for this, but something still seems off. This is what I see when I try to start the alias App. Same happens when I double click to open this app manually from its App folder.
<img width="258" alt="Screenshot 2022-06-20 at 20 15 51" src="https://user-images.githubusercontent.com/84964395/174665907-441a791f-16c8-49e7-a514-0e9f6b1112ac.png">
 
I'm not able to attach the **info.plist** file. Here is the bit that the pop-up window text referred to:
```
	<key>PyRuntimeLocations</key>
	<array>
		<string>@executable_path/../Frameworks/libpython3.7.dylib</string>
		<string>/Users/SophieApple/.pyenv/versions/3.7.4/lib/libpython3.7.dylib</string>
	</array>
```

**Comment by SophiaDesign** [comment]
> hey, I'm back from paternity leave. Variable COLRv1 is not supported yet in the latest stable versions of fontmake and related libraries. There's a work-in-progress branch of fonttools named [`wip-variable-colr`](https://github.com/fonttools/fonttools/tree/wip-variable-colr) where I added initial support for merging masters with compatible COLRv1 tables into a variable COLRv1. This is handled automatically by varLib like the rest of the variable tables, so running fontmake from that fonttools branch should just work, though it probably needs more testing and polishing.
> 
> If you want to try this out, install fonttools from the wip-variable-colr branch after you installed latest fontmake as usual, e.g.:
> 
> ```
> pip install -e git+https://github.com/fonttools/fonttools.git@wip-variable-colr#egg=FontTools
> ```

@anthrotype Welcome back.

I tried this two ways. First with `gftools builder` and got this: 

```
(venv) sources gftools builder config.yaml
Traceback (most recent call last):
  File "/Users/SophieApple/Desktop/WORKS/2021-projects/GF-Foldit-GoogleFonts2021/Project/GF-Foldit/venv/bin/gftools-builder.py", line 17, in <module>
    from gftools.builder import GFBuilder
  File "/Users/SophieApple/Desktop/WORKS/2021-projects/GF-Foldit-GoogleFonts2021/Project/GF-Foldit/venv/lib/python3.7/site-packages/gftools/builder/__init__.py", line 110, in <module>
    from gftools.builder.autohint import autohint
  File "/Users/SophieApple/Desktop/WORKS/2021-projects/GF-Foldit-GoogleFonts2021/Project/GF-Foldit/venv/lib/python3.7/site-packages/gftools/builder/autohint.py", line 1, in <module>
    from ttfautohint import ttfautohint
  File "/Users/SophieApple/Desktop/WORKS/2021-projects/GF-Foldit-GoogleFonts2021/Project/GF-Foldit/venv/lib/python3.7/site-packages/ttfautohint/__init__.py", line 13, in <module>
    from ttfautohint import memory
  File "/Users/SophieApple/Desktop/WORKS/2021-projects/GF-Foldit-GoogleFonts2021/Project/GF-Foldit/venv/lib/python3.7/site-packages/ttfautohint/memory.py", line 18, in <module>
    raise OSError("Could not find the libc shared library")
OSError: Could not find the libc shared library
```

I assume might be an issue after my OS update. I am now on MacOS Monterey version 12.4 (21F79). Previously I got the same result as with using `fontmake` here:

```
(venv) sources fontmake GF-Foldit-decomposed.glyphs -o variable
INFO:fontmake.font_project:Building master UFOs and designspace from Glyphs source
INFO:glyphsLib.classes:Parsing "GF-Foldit-decomposed.glyphs" file into <GSFont>
WARNING:glyphsLib.builder.builders.UFOBuilder:Non-existent glyph class public.kern2.a found in kerning rules.
INFO:fontmake.font_project:Building variable font variable_ttf/Foldit-VF.ttf
INFO:ufo2ft:Pre-processing glyphs
INFO:ufo2ft.filters.base:Running EraseOpenCornersFilter on Foldit-Thin-Condensed
INFO:ufo2ft.filters.base:Running EraseOpenCornersFilter on Foldit-ExtraBold-Expanded
INFO:ufo2ft.filters.base:Running EraseOpenCornersFilter on Foldit-Black-Expanded
INFO:cu2qu.ufo:New spline lengths: 1: 24, 2: 20
INFO:ufo2ft.filters.base:Running DecomposeComponentsFilter on Foldit-Thin-Condensed
INFO:ufo2ft.filters.base:Running DecomposeComponentsFilter on Foldit-ExtraBold-Expanded
INFO:ufo2ft.filters.base:Running DecomposeComponentsFilter on Foldit-Black-Expanded
INFO:ufo2ft:Building OpenType tables for Foldit-Thin-Condensed
INFO:ufo2ft:Building OpenType tables for Foldit-ExtraBold-Expanded
INFO:ufo2ft:Building OpenType tables for Foldit-Black-Expanded
INFO:ufo2ft:Building variable TTF font
INFO:fontTools.varLib:Axes:
[{'axisLabels': [],
  'axisOrdering': None,
  'default': 100.0,
  'hidden': False,
  'labelNames': {'en': 'Weight'},
  'map': [],
  'maximum': 900.0,
  'minimum': 100.0,
  'name': 'Weight',
  'tag': 'wght'}]
INFO:fontTools.varLib:Internal master locations:
[{'Weight': 100.0}, {'Weight': 700.0}, {'Weight': 900.0}]
INFO:fontTools.varLib:Internal axis supports:
{'Weight': [100.0, 100.0, 900.0]}
INFO:fontTools.varLib:Normalized master locations:
[{'Weight': 0.0}, {'Weight': 0.75}, {'Weight': 1.0}]
INFO:fontTools.varLib:Index of base master: 0
INFO:fontTools.varLib:Building variable font
INFO:fontTools.varLib:Loading master fonts
INFO:fontTools.varLib:Generating fvar
INFO:fontTools.varLib:Generating avar
INFO:fontTools.varLib:No need for avar
INFO:fontTools.varLib:Building variations tables
INFO:fontTools.varLib:Generating MVAR
INFO:fontTools.varLib:	cpht: OS/2.sCapHeight	[700, 730, 730]
INFO:fontTools.varLib:	xhgt: OS/2.sxHeight	[500, 530, 530]
INFO:fontTools.varLib:	stro: OS/2.yStrikeoutPosition	[300, 318, 318]
INFO:fontTools.varLib:Generating HVAR
INFO:fontTools.varLib:Merging OpenType Layout tables
INFO:fontTools.varLib:Generating gvar
INFO:fontTools.varLib:Merging TT hinting
fontmake: Error: In 'GF-Foldit-decomposed.glyphs' -> 'master_ufo/Foldit.designspace': Generating fonts from Designspace failed: 

Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation: COLR.ta
ble.BaseGlyphList.BaseGlyphPaintRecord[429].Paint.Paint.ColorLine.StopCount

The problem is likely to be in Foldit ExtraBold-Expanded:
Expected to see .StopCount==3, instead saw 2
```

**Comment by anthrotype** [comment]
(technically ufo2ft's `variable-colr` branch is not needed by fontgoggles, but you will probably need if you want to build variable CORLv1 with fontmake so get that one too)

**Comment by anthrotype** [comment]
So the varLib.merge errors you see when you try to compile with fontmake with work-in-progress variable COLR support haver to do with the fact that your sources contain incompatible linear gradient definitions in the various masters.
For the merging to work, each master hazs to have exactly the same color glyphs, each same-named glyph has to have the same number of gradients, each respective gradient's color line has to have the same number of color stops, each color stop has to use the same palette index (i.e. the same color), etc.
If in one master a gradients has, say, three color stops where in the others it has two, it will fail.
Or you have two color stops, but in one master the first and last stop's colors are inverted, you'll get an error. etc.

So you should go and make sure that the sources are compatible.

I know, this is all very rough and subject to change. The toolings are not ready yet for regular users, so apologies if you have been unknowingly thrown into this and find yourself stuck.

honestly, I would strongly recommend that you return to this variable COLRv1 thing later this year, say, around September, when I hope we will have something published in the stable branch of the font build pipeline.
But, if you feel brave, I do do appreciate you trying out develoment versions of our tools and submit bug reports/feature request! Thanks :)

**Comment by anthrotype** [comment]
fonttools 4.34.0 and ufo2ft 2.28.0 were just released, try see if you can make some progress building your variable COLR using them

**Comment by justvanrossum** [comment]
I just released blackrenderer 0.5.2 with Cosimo's variable COLRv1 work included.

I would love to know how well it works with this font before I push a FontGoggles release that uses blackrenderer 0.5.2.

**Comment by lenaweber404** [comment]
> 

Hi everyone! I'm working on a similar font as Sophia. (variable outlines + variable gradients).
With fonttools  4.33.3 and ufo2ft 2.27.0 I was able to export a ttf, after the update I repeatetly get the error: `Generating fonts from Designspace failed: 'list' object has no attribute 'exend' `

Thank you for your work on this project, truly amazing stuff!

**Comment by justvanrossum** [comment]
Ouch, a typo in fonttools indeed:

https://github.com/fonttools/fonttools/blob/2a07518b700e1301b8b1d2d90fafdc0c6c966b60/Lib/fontTools/varLib/merger.py#L1429

**Comment by anthrotype** [comment]
Ouch indeed! Sorry!

**Comment by SophiaDesign** [comment]
@anthrotype I tested with `fontmake` and got

```
fontmake: Error: In 'Foldit-test.glyphs' -> 'master_ufo/Foldit.designspace': Generating fonts from Designspace failed: 

Couldn't merge the fonts, because a list of objects had inconsistent lengths.
This happened while performing the following operation:
COLR.table.BaseGlyphList.BaseGlyphPaintRecord[0].Paint.Layers

The problem is likely to be in Foldit Thin-origin (base glyph 'O'):
Expected to see .Layers==4, instead saw 20
```

You can see the test file attached. It does not seem to have the identified problem in the Thin master. What could be the issue?
[Foldit-test.glyphs.zip](https://github.com/SophiaDesign/Foldit/files/9072747/Foldit-test.glyphs.zip)

**Comment by anthrotype** [comment]
The error is saying that glyph 'O' has different number of color layers across masters, isn't that true? It might be that the name of the reported master is not correct, but the underlying issue is the different number of layers, all non default masters have to have the same number of layers as the default master, at the individual glyph level.

**Comment by SophiaDesign** [comment]
On the Glyphs interface it looks like they all have the same number of layers. Is there any other way I can check this? @anthrotype

**Comment by anthrotype** [comment]
You could export .glyphs source to UFOs using fontmake -o ufo and then inspect the content of the master UFOs's lib.plist, the key named colorGlyphs, make sure the 'O' glyph has the same number of layers in all masters and if they make sense.. I'm actually on holiday until 18 July.

**Comment by justvanrossum** [comment]
The glyph /O in the ufo's all expand to four color layers, but somehow it expands to 20 color layers in Foldit-Thin-origin.ufo:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/4246121/178062545-1274335f-078c-4a0c-8dca-45415a78502f.png">

**Comment by vv-monsalve** [comment]
I wonder if this could be related to the incompatible linear gradient definitions in the various masters that Cosimo [mentioned](https://github.com/SophiaDesign/Foldit/issues/2#issuecomment-1164705917) above? Have you inspected/solve this already?

> but the underlying issue is the different number of layers, all non default masters have to have the same number of layers as the default master, at the individual glyph level.

And also to this. From what I've seen in the source file, there are only color layers and not a default master layer.

Perhaps @mekkablue could be of any help on how better to handle these Color gradients from the glyphs source file. Beyond what has been already reported in the forum ([here](https://forum.glyphsapp.com/t/gradient-missing-in-exported-files/20668/2), [here](https://forum.glyphsapp.com/t/gradient-transform/22169/9) and related to gradients in [here](https://forum.glyphsapp.com/t/multiple-color-layers/20685))

**Comment by mekkablue** [comment]
Excuses for not having read the complete thread (TL). COLR/CPAL should have a fallback layer. In Glyphs, the COLR layers/glyphs derive their widths from the default master layer. Some renderers may require the fallback for reserving pixel space for rendering (otherwise your risk clipping). 

COLRv1 support is in the works and will be rolled out in a few months the earliest. You can sign up for the beta tester program, ping me in the Glyphs forum with a DM.

**Comment by anthrotype** [comment]
> COLR/CPAL should have a fallback layer. In Glyphs, the COLR layers/glyphs derive their widths from the default master layer. Some renderers may require the fallback for reserving pixel space for rendering (otherwise your risk clipping).

Yes, that is true for COLR version 0 on Safari / macOS, but for COLR version 1 it's no longer needed since there are distinct clipBox data in the COLRv1 table itself, and even when that is missing the renderers that do support v1, can figure out that ar runtime

**Comment by SophiaDesign** [comment]
> I wonder if this could be related to the incompatible linear gradient definitions in the various masters that Cosimo [mentioned](https://github.com/SophiaDesign/Foldit/issues/2#issuecomment-1164705917) above? Have you inspected/solve this already?

Yep, all gradients should be compatible based on [Cosimo's description](https://github.com/SophiaDesign/Foldit/issues/2#issuecomment-1164705917). 
Each gradient element has:
- the same number of colour stops
- exactly the same colours
- colour stops are pointing in the same direction

**Comment by khaledhosny** [comment]
> @anthrotype I tested with `fontmake` and got
> 
> ```
> fontmake: Error: In 'Foldit-test.glyphs' -> 'master_ufo/Foldit.designspace': Generating fonts from Designspace failed: 
> 
> Couldn't merge the fonts, because a list of objects had inconsistent lengths.
> This happened while performing the following operation:
> COLR.table.BaseGlyphList.BaseGlyphPaintRecord[0].Paint.Layers
> 
> The problem is likely to be in Foldit Thin-origin (base glyph 'O'):
> Expected to see .Layers==4, instead saw 20
> ```
> 
> You can see the test file attached. It does not seem to have the identified problem in the Thin master. What could be the issue? [Foldit-test.glyphs.zip](https://github.com/SophiaDesign/Foldit/files/9072747/Foldit-test.glyphs.zip)

The Thin master has four extra color layers, these are the source of the error:
<img width="180" alt="Screen Shot 2022-07-14 at 4 46 07 PM" src="https://user-images.githubusercontent.com/93914/179010829-88434650-74a3-45cb-85a3-4dde59f4b253.png">

**Comment by SophiaDesign** [comment]
https://user-images.githubusercontent.com/84964395/179035289-f30b7d76-1766-45c9-8766-71324a9449bb.mp4

**Comment by SophiaDesign** [comment]
Update: it's working, I just had to get the new FontGoggles. 

We have a fully functional variable-gradient COLRv1 font here 🎉🎉🎉 Thank you everyone this is truly amazing

https://user-images.githubusercontent.com/84964395/179042317-ba27899d-79fd-4b2c-ac29-bbf963e39955.mp4

**Comment by SophiaDesign** [comment]
Hello, just opening this up again, as I worked through the source file and there are a few glyphs left with issues, which I am not able to identify/fix on the Glyphs interface: 
- M
```
fontmake: Error: In 'Foldit-decomposed.glyphs' -> 'master_ufo/Foldit.designspace': Generating fonts from Designspace failed: 

Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation: COLR.ta
ble.BaseGlyphList.BaseGlyphPaintRecord[97].Paint.Layers[0].Paint.ColorLine.Col
orStop[1].PaletteIndex

The problem is likely to be in Foldit Thin-origin (base glyph 'M'):
Expected to see .PaletteIndex==4, instead saw 2
```
- circumflexhookabove (and glyphs using this component)
```
fontmake: Error: In 'Foldit-decomposed.glyphs' -> 'master_ufo/Foldit.designspace': Generating fonts from Designspace failed: 

Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation: COLR.ta
ble.BaseGlyphList.BaseGlyphPaintRecord[244].Paint.Layers[5].Paint.ColorLine.Co
lorStop[1].PaletteIndex

The problem is likely to be in Foldit Thin-origin (base glyph 'ecircumflexhookabove'):
Expected to see .PaletteIndex==2, instead saw 4
```
- guillemeright
```
ERROR:fontmake.compatibility:Fonts had differing number of contours in glyph guillemetright.color0:
ERROR:fontmake.compatibility: * Foldit Thin-origin had 1
ERROR:fontmake.compatibility: * 7 fonts had 2
ERROR:fontmake.compatibility:Fonts had differing number of contours in glyph guillemetright.color1:
ERROR:fontmake.compatibility: * Foldit Thin-origin, Foldit Light had 1
ERROR:fontmake.compatibility: * Foldit Regular, Foldit Medium, Foldit SemiBold, Foldit Bold, Foldit ExtraBold-origin, Foldit Black-origin had 2
ERROR:fontmake.compatibility:Fonts had differing number of contours in glyph guillemetright.color2:
ERROR:fontmake.compatibility: * Foldit Thin-origin had 2
ERROR:fontmake.compatibility: * Foldit Light had 1
```
- trademark
```
fontmake: Error: In 'Foldit-decomposed.glyphs' -> 'master_ufo/Foldit.designspace': Generating fonts from Designspace failed: 

Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation: COLR.ta
ble.BaseGlyphList.BaseGlyphPaintRecord[481].Paint.Layers[0].Paint.ColorLine.Co
lorStop[1].PaletteIndex

The problem is likely to be in Foldit Thin-origin (base glyph 'trademark'):
Expected to see .PaletteIndex==4, instead saw 2
```
- Won
```
fontmake: Error: In 'Foldit-decomposed.glyphs' -> 'master_ufo/Foldit.designspace': Generating fonts from Designspace failed: 

Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation: COLR.ta
ble.BaseGlyphList.BaseGlyphPaintRecord[508].Paint.Layers[4].Paint.ColorLine.Co
lorStop[0].PaletteIndex

The problem is likely to be in Foldit Thin-origin (base glyph 'won'):
Expected to see .PaletteIndex==5, instead saw 1
```

All are marked in red in the `Foldit-origin.glyphs` file and have been removed from `Foldit-decomposed.glyphs` file to test the exporting.

I'm looking for any suggestions: What else can I use to find out where and what the compatibility issue is with the glyphs listed above?

**Files: [Foldit-files-20July2022.zip](https://github.com/SophiaDesign/Foldit/files/9151527/Foldit-files-20July2022.zip)**
 These are Source files + Working variable-gradient font (but with missing glyphs)

**Comment by khaledhosny** [comment]
> The problem is likely to be in Foldit Thin-origin (base glyph 'M'):
> Expected to see .PaletteIndex==4, instead saw 2

The `PaletteIndex` errors like these mean there is a mismatch in colors between the masters (even if it is very slight variation). Make sure all colors have the same hex value across layers.

**Comment by SophiaDesign** [comment]
**All glyphs are fixed except Won** currency symbol. Could too many colour stops on a single gradient cause an issue?

**Comment by SophiaDesign** [comment]
Could not find/fix the Won glyph issue in Glyphs app, but I changed the UFO file: [Foldit-UFO.zip](https://github.com/SophiaDesign/Foldit/files/9270557/Foldit-UFO.zip)

I am not able to use the UFOs to create a variable font using **fontmake**:
`fontmake: error: Glyphs or designspace source required for variable font`

**Comment by vv-monsalve** [comment]
> I am not able to use the UFOs to create a variable font using **fontmake**:

You should provide a `.designspace` file to build a VF. A base one is generated and included by `glyphsLib`in the `master_ufo` dir when converting the .glyphs source to master-ufos + designspace. 

You would like to read [Fontmake's Trubleshooting doc](https://github.com/googlefonts/fontmake/blob/main/TROUBLESHOOTING.md) for more details.

**Comment by vv-monsalve** [comment]
> **All glyphs are fixed except Won** currency symbol. Could too many colour stops on a single gradient cause an issue?

Are you receiving a particular message about it? 

In any case, simplifying as much as possible is always helpful. The `Won` glyph does have many outlines + stop gradients, and there are more masters than ideal in the file, too (as mentioned in the design space issue.) I would suggest first reducing the number of masters, it will also simplify the designspace before you use it to build the font.

Otho, please inspect the comment on the Outlines quality issue.

**Comment by SophiaDesign** [comment]
@vv-monsalve The issue with Won remained the same as posted [here](https://github.com/SophiaDesign/Foldit/issues/2#issuecomment-1190427665) above. It failed to create a designspace file, so I am left with UFO files. 

It suggests the **Foldit Thin** has an incompatibility issue on one of the color palette index. I modified this in the `Foldit-Thin-origin.ufo` file based on suggestion in the error message. [Attached here](**url**) but I don't know how to go from here unfortunately.

I don't see any colour point differences in the masters using Glyphs. I assume the issue will be in one of the crossbars as there was no issue with `W.glyph`. It's possible that I simply can't spot the difference as I worked on (and stared at) it for too long.

**Comment by vv-monsalve** [comment]
> @vv-monsalve The issue with `Won.glyph` remained the same as posted [here](https://github.com/SophiaDesign/Foldit/issues/2#issuecomment-1190427665) above. It failed to create a designspace file, so I am left with UFO files.

In that case, there should be the same mismatching colors that Khaled mentioned above. 

The link to the error message is not working, so I can't inspect it.

> I assume the issue will be in one of the crossbars as there was no issue with `W.glyph`

You could generate a temporary glyphs file with only that glyph where you can try to confirm the export step by step. Adding one crossbar at a time so that it would tell you which is failing. In this regard, it would be really helpful for you to reduce the number of masters as said in the other issue.
